import Head from 'next/head';
import { LayoutChat } from '@/layouts/chat';
import { Header } from '@/components/header';
import { LayoutChatModal } from '@/layouts/chat-modal';

export default function Chat() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <LayoutChat />

      <LayoutChatModal />
    </>
  );
}
